language: objective-c

before_install:
- gem install cocoapods
- npm install -g bower
- bower install

script:
- cd bower_components/whatsmyip-core && bundle exec middleman build && cd - && xctool test
